# Generated by Django 6.0 on 2026-02-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Província')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Províncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='core.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['provincia__nome', 'nome'],
                'unique_together': {('provincia', 'nome')},
            },
        ),
    ]
