# Generated by Django 6.0 on 2026-02-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Província')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Províncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='core.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['provincia__nome', 'nome'],
                'unique_together': {('provincia', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_drh', models.IntegerField(help_text='ID original do candidato no sistema DRH', unique=True, verbose_name='ID no Sistema DRH')),
                ('codigo_candidato', models.CharField(help_text='Código único gerado pelo DRH', max_length=20, unique=True, verbose_name='Código do Candidato')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Género')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('numero_bi', models.CharField(max_length=20, verbose_name='Número de BI')),
                ('numero_telefone', models.CharField(max_length=15, verbose_name='Número de Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('tipo_agente', models.CharField(choices=[('MMV', 'Membro de Mesa de Voto'), ('AGENTE_CIVICO', 'Agente de Educação Cívica'), ('FORMADOR', 'Formador'), ('BRIGADISTA', 'Brigadista')], default='BRIGADISTA', help_text='Tipo de agente eleitoral para formação', max_length=20, verbose_name='Tipo de Agente')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidatos_formacao/fotos/', verbose_name='Foto')),
                ('data_recepcao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Recepção do DRH')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_formacao', to='core.distrito', verbose_name='Distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_formacao', to='core.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'Candidato em Formação',
                'verbose_name_plural': 'Candidatos em Formação',
                'ordering': ['-data_recepcao'],
            },
        ),
    ]
