# Generated by Django 6.0 on 2026-02-13 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CENTRAL', 'STAE Central'), ('PROVINCIAL', 'STAE Provincial'), ('DISTRITAL', 'STAE Distrital')], default='DISTRITAL', max_length=20, verbose_name='Nível Administrativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(blank=True, help_text='Distrito de responsabilidade (obrigatório para Distrital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_distritais_defc', to='core.distrito', verbose_name='Distrito')),
                ('provincia', models.ForeignKey(blank=True, help_text='Província de responsabilidade (obrigatório para Provincial e Distrital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_provinciais_defc', to='core.provincia', verbose_name='Província')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizadores',
            },
        ),
    ]
