# Generated by Django 6.0 on 2026-02-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilutilizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_ativo', models.CharField(choices=[('RECENSEAMENTO', 'Recenseamento Eleitoral'), ('VOTACAO', 'Votação')], default='RECENSEAMENTO', help_text='Controla os tipos de formação permitidos (ex: Brigadistas no Recenseamento, MMV na Votação)', max_length=20, verbose_name='Período Eleitoral Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
