# Generated by Django 6.0 on 2026-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilutilizador',
            name='deve_alterar_senha',
            field=models.BooleanField(default=True, help_text='Se True, o utilizador é forçado a definir uma nova senha no próximo login.', verbose_name='Deve Alterar Senha'),
        ),
    ]
