# Generated by Django 6.0 on 2025-12-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Distrito')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Província')),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Províncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CENTRAL', 'STAE Central'), ('PROVINCIAL', 'STAE Provincial'), ('DISTRITAL', 'STAE Distrital')], default='DISTRITAL', max_length=20, verbose_name='Nível Administrativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(blank=True, help_text='Distrito de responsabilidade (obrigatório para Distrital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_distritais', to='candidaturas.distrito', verbose_name='Distrito')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('provincia', models.ForeignKey(blank=True, help_text='Província de responsabilidade (obrigatório para Provincial e Distrital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_provinciais', to='candidaturas.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizadores',
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='candidaturas.provincia', verbose_name='Província'),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Género')),
                ('funcao', models.CharField(choices=[('FORMADOR', 'Formador'), ('BRIGADISTA', 'Brigadista'), ('AGENTE_CIVICO', 'Agente de Educação Cívica')], default='BRIGADISTA', max_length=20, verbose_name='Vaga a Candidatar')),
                ('numero_bi', models.CharField(max_length=20, unique=True, verbose_name='Número de BI')),
                ('numero_telefone', models.CharField(max_length=15, verbose_name='Número de Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço (Bairro/Rua)')),
                ('arquivo_cv', models.FileField(blank=True, null=True, upload_to='candidatos/cv/', verbose_name='Curriculum Vitae (CV)')),
                ('arquivo_bi', models.FileField(blank=True, null=True, upload_to='candidatos/bi/', verbose_name='Cópia do BI')),
                ('arquivo_certificado', models.FileField(blank=True, null=True, upload_to='candidatos/certificados/', verbose_name='Certificado de Habilitações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidatos/fotos/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DOCS_APROVADOS', 'Documentos Aprovados'), ('DOCS_REJEITADOS', 'Documentos Rejeitados'), ('ENTREVISTA_AGENDADA', 'Entrevista Agendada'), ('ENTREVISTA_APROVADA', 'Aprovado na Entrevista'), ('ENTREVISTA_REPROVADA', 'Reprovado na Entrevista'), ('CONTRATADO', 'Contratado/Credenciais Geradas')], default='PENDENTE', max_length=20, verbose_name='Estado da Candidatura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_entrevista', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrevista')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='candidaturas.distrito', verbose_name='Distrito')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='candidaturas.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('provincia', 'nome')},
        ),
    ]
