# Generated by Django 6.0 on 2025-12-29 09:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCandidato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Género')),
                ('funcao', models.CharField(choices=[('FORMADOR', 'Formador'), ('BRIGADISTA', 'Brigadista'), ('AGENTE_CIVICO', 'Agente de Educação Cívica')], default='BRIGADISTA', max_length=20, verbose_name='Vaga a Candidatar')),
                ('numero_bi', models.CharField(db_index=True, max_length=20, verbose_name='Número de BI')),
                ('numero_telefone', models.CharField(max_length=15, verbose_name='Número de Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço (Bairro/Rua)')),
                ('arquivo_cv', models.TextField(blank=True, max_length=100, null=True, verbose_name='Curriculum Vitae (CV)')),
                ('arquivo_bi', models.TextField(blank=True, max_length=100, null=True, verbose_name='Cópia do BI')),
                ('arquivo_certificado', models.TextField(blank=True, max_length=100, null=True, verbose_name='Certificado de Habilitações')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DOCS_APROVADOS', 'Documentos Aprovados'), ('DOCS_REJEITADOS', 'Documentos Rejeitados'), ('ENTREVISTA_AGENDADA', 'Entrevista Agendada'), ('ENTREVISTA_APROVADA', 'Aprovado na Entrevista'), ('ENTREVISTA_REPROVADA', 'Reprovado na Entrevista'), ('CONTRATADO', 'Contratado/Credenciais Geradas')], default='PENDENTE', max_length=20, verbose_name='Estado da Candidatura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_entrevista', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrevista')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('distrito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.distrito', verbose_name='Distrito')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.provincia', verbose_name='Província')),
            ],
            options={
                'verbose_name': 'historical Candidato',
                'verbose_name_plural': 'historical Candidatos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfilUtilizador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CENTRAL', 'STAE Central'), ('PROVINCIAL', 'STAE Provincial'), ('DISTRITAL', 'STAE Distrital')], default='DISTRITAL', max_length=20, verbose_name='Nível Administrativo')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('distrito', models.ForeignKey(blank=True, db_constraint=False, help_text='Distrito de responsabilidade (obrigatório para Distrital)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.distrito', verbose_name='Distrito')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(blank=True, db_constraint=False, help_text='Província de responsabilidade (obrigatório para Provincial e Distrital)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.provincia', verbose_name='Província')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'historical Perfil de Utilizador',
                'verbose_name_plural': 'historical Perfis de Utilizadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
