# Generated by Django 6.0 on 2025-12-29 09:55

from django.db import migrations
from django.utils import timezone
import datetime

def criar_vagas_iniciais_e_migrar(apps, schema_editor):
    Vaga = apps.get_model('candidaturas', 'Vaga')
    Candidato = apps.get_model('candidaturas', 'Candidato')
    
    # 1. Criar Vagas Padrão
    vagas_map = {
        'BRIGADISTA': Vaga.objects.create(
            titulo='Brigadista',
            descricao='Responsável pelo registo eleitoral no terreno.',
            data_inicio=timezone.now().date(),
            data_fim=timezone.now().date() + datetime.timedelta(days=365),
            ativa=True
        ),
        'FORMADOR': Vaga.objects.create(
            titulo='Formador Provincial',
            descricao='Formador de agentes eleitorais.',
            data_inicio=timezone.now().date(),
            data_fim=timezone.now().date() + datetime.timedelta(days=365),
            ativa=True
        ),
        'AGENTE_CIVICO': Vaga.objects.create(
            titulo='Agente de Educação Cívica',
            descricao='Promotor da educação cívica eleitoral.',
            data_inicio=timezone.now().date(),
            data_fim=timezone.now().date() + datetime.timedelta(days=365),
            ativa=True
        )
    }
    
    # 2. Migrar Candidatos existentes
    for candidato in Candidato.objects.all():
        if candidato.funcao in vagas_map:
            candidato.vaga = vagas_map[candidato.funcao]
            candidato.save()
        else:
            print(f"AVISO: Candidato {candidato.id} tem função desconhecida: {candidato.funcao}")

def reverter_migracao(apps, schema_editor):
    Vaga = apps.get_model('candidaturas', 'Vaga')
    Candidato = apps.get_model('candidaturas', 'Candidato')
    
    # Limpar relação
    Candidato.objects.update(vaga=None)
    # Apagar vagas
    Vaga.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_vaga_historicalvaga_candidato_vaga_and_more'),
    ]

    operations = [
        migrations.RunPython(criar_vagas_iniciais_e_migrar, reverter_migracao),
    ]

