# Generated by Django 6.0 on 2025-12-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0004_migrar_dados_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='historicalcandidato',
            name='funcao',
        ),
        migrations.AddField(
            model_name='provincia',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
