# Generated by Django 6.0 on 2025-12-29 10:20

from django.db import migrations

def popular_coordenadas(apps, schema_editor):
    Provincia = apps.get_model('candidaturas', 'Provincia')
    
    # Coordenadas aproximadas (Centroids)
    dados = {
        'Maputo Cidade': (-25.9692, 32.5732),
        'Maputo Província': (-25.5, 32.5),
        'Gaza': (-23.8, 33.5),
        'Inhambane': (-23.8661, 35.3833),
        'Sofala': (-19.8436, 34.8389),
        'Manica': (-19.1167, 33.4833),
        'Tete': (-16.1564, 33.5867),
        'Zambézia': (-16.5, 37.0),
        'Nampula': (-15.1167, 39.2667), 
        'Niassa': (-12.5, 36.5), 
        'Cabo Delgado': (-12.5, 39.5) 
    }
    
    for nome, (lat, lon) in dados.items():
        Provincia.objects.filter(nome__icontains=nome.split(' ')[0]).update(latitude=lat, longitude=lon)
        # Fallback especifico para 'Maputo' vs 'Maputo Cidade' se necessario, mas o filter acima pega. 
        # Update preciso:
    
    # Reforçar Maputo Cidade vs Maputo Provincia se nomes forem exatos no DB 
    Provincia.objects.filter(nome='Maputo Cidade').update(latitude=-25.9692, longitude=32.5732)
    Provincia.objects.filter(nome='Maputo Província').update(latitude=-25.5, longitude=32.5)

class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0005_remove_candidato_funcao_and_more'),
    ]

    operations = [
        migrations.RunPython(popular_coordenadas),
    ]
