# Generated by Django 6.0 on 2026-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0006_popular_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='validacao_atestado_medico',
            field=models.BooleanField(default=False, verbose_name='Atestado Médico'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_bi',
            field=models.BooleanField(default=False, verbose_name='BI Válido'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_certificado',
            field=models.BooleanField(default=False, verbose_name='Certificado Válido'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_cv',
            field=models.BooleanField(default=False, verbose_name='CV Válido'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_nuit',
            field=models.BooleanField(default=False, verbose_name='NUIT (Se aplicável)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_registo_criminal',
            field=models.BooleanField(default=False, verbose_name='Registo Criminal'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='validacao_requerimento',
            field=models.BooleanField(default=False, verbose_name='Requerimento Assinado'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_atestado_medico',
            field=models.BooleanField(default=False, verbose_name='Atestado Médico'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_bi',
            field=models.BooleanField(default=False, verbose_name='BI Válido'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_certificado',
            field=models.BooleanField(default=False, verbose_name='Certificado Válido'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_cv',
            field=models.BooleanField(default=False, verbose_name='CV Válido'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_nuit',
            field=models.BooleanField(default=False, verbose_name='NUIT (Se aplicável)'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_registo_criminal',
            field=models.BooleanField(default=False, verbose_name='Registo Criminal'),
        ),
        migrations.AddField(
            model_name='historicalcandidato',
            name='validacao_requerimento',
            field=models.BooleanField(default=False, verbose_name='Requerimento Assinado'),
        ),
    ]
