# Generated by Django 6.0 on 2026-02-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaga',
            name='requer_formacao',
            field=models.BooleanField(default=True, help_text='Se marcado, candidatos aprovados serão enviados para formação no DEFC. Caso contrário, são contratados diretamente.', verbose_name='Requer Formação'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='requer_formacao',
            field=models.BooleanField(default=True, help_text='Se marcado, candidatos aprovados serão enviados para formação no DEFC. Caso contrário, são contratados diretamente.', verbose_name='Requer Formação'),
        ),
    ]
