# Generated by Django 6.0 on 2026-02-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0002_historicalvaga_requer_formacao_vaga_requer_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaga',
            name='documentos_necessarios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de documentos que os candidatos devem submeter para esta vaga', verbose_name='Documentos Necessários'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='documentos_necessarios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de documentos que os candidatos devem submeter para esta vaga', verbose_name='Documentos Necessários'),
        ),
    ]
