# Generated by Django 6.0 on 2026-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_historicalvaga_documentos_necessarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaga',
            name='nivel_aprovacao',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central (STAE Central)'), ('PROVINCIAL', 'Nível Provincial'), ('DISTRITAL', 'Nível Distrital')], default='DISTRITAL', help_text='Define qual nível hierárquico é responsável por aprovar as candidaturas desta vaga.', max_length=20, verbose_name='Nível de Aprovação'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='nivel_aprovacao',
            field=models.CharField(choices=[('CENTRAL', 'Nível Central (STAE Central)'), ('PROVINCIAL', 'Nível Provincial'), ('DISTRITAL', 'Nível Distrital')], default='DISTRITAL', help_text='Define qual nível hierárquico é responsável por aprovar as candidaturas desta vaga.', max_length=20, verbose_name='Nível de Aprovação'),
        ),
    ]
