# Generated by Django 6.0 on 2026-02-11 10:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0004_historicalvaga_nivel_aprovacao_vaga_nivel_aprovacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalcandidato',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical candidato', 'verbose_name_plural': 'historical candidatos'},
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(help_text='Ex: Sala 2, STAE Central ou Link Google Meet', max_length=200, verbose_name='Local')),
                ('nota_tecnica', models.IntegerField(default=0, verbose_name='Nota Técnica (0-20)')),
                ('nota_comunicacao', models.IntegerField(default=0, verbose_name='Nota Comunicação (0-20)')),
                ('nota_experiencia', models.IntegerField(default=0, verbose_name='Nota Experiência (0-20)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Entrevistador')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTOU', 'Não Compareceu')], default='AGENDADA', max_length=20, verbose_name='Status da Entrevista')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20, verbose_name='Resultado Final')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_detalhe', to='candidaturas.candidato', verbose_name='Candidato')),
                ('entrevistador', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntrevista',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(help_text='Ex: Sala 2, STAE Central ou Link Google Meet', max_length=200, verbose_name='Local')),
                ('nota_tecnica', models.IntegerField(default=0, verbose_name='Nota Técnica (0-20)')),
                ('nota_comunicacao', models.IntegerField(default=0, verbose_name='Nota Comunicação (0-20)')),
                ('nota_experiencia', models.IntegerField(default=0, verbose_name='Nota Experiência (0-20)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Entrevistador')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTOU', 'Não Compareceu')], default='AGENDADA', max_length=20, verbose_name='Status da Entrevista')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20, verbose_name='Resultado Final')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.candidato', verbose_name='Candidato')),
                ('entrevistador', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Candidato',
                'verbose_name_plural': 'historical Candidatos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
