# Generated by Django 6.0 on 2026-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0005_alter_candidato_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='entrevista',
            options={'ordering': ['data_hora'], 'verbose_name': 'Entrevista', 'verbose_name_plural': 'Entrevistas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcandidato',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Candidato', 'verbose_name_plural': 'historical Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='historicalentrevista',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Entrevista', 'verbose_name_plural': 'historical Entrevistas'},
        ),
        migrations.AddField(
            model_name='historicalvaga',
            name='concurso_aberto',
            field=models.BooleanField(default=False, verbose_name='Concurso Aberto'),
        ),
        migrations.AddField(
            model_name='historicalvaga',
            name='documento_concurso',
            field=models.TextField(blank=True, help_text='PDF oficial gerado aquando da abertura do concurso.', max_length=100, null=True, verbose_name='Documento do Concurso'),
        ),
        migrations.AddField(
            model_name='historicalvaga',
            name='numero_vagas',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de vagas disponíveis especificadas na abertura do concurso.', null=True, verbose_name='Número de Vagas'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='concurso_aberto',
            field=models.BooleanField(default=False, verbose_name='Concurso Aberto'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='documento_concurso',
            field=models.FileField(blank=True, help_text='PDF oficial gerado aquando da abertura do concurso.', null=True, upload_to='vagas/concursos/', verbose_name='Documento do Concurso'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='numero_vagas',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de vagas disponíveis especificadas na abertura do concurso.', null=True, verbose_name='Número de Vagas'),
        ),
    ]
