# Generated by Django 6.0 on 2026-03-05 22:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0006_alter_candidato_options_alter_entrevista_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistadorVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Entrevistador')),
                ('codigo_acesso', models.CharField(help_text='O código gerado automaticamente que o entrevistador usará como senha.', max_length=20, unique=True, verbose_name='Código de Acesso')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistador_vaga', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador do Sistema')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistadores', to='candidaturas.vaga', verbose_name='Vaga Alocada')),
            ],
            options={
                'verbose_name': 'Entrevistador da Vaga',
                'verbose_name_plural': 'Entrevistadores da Vaga',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntrevistadorVaga',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Entrevistador')),
                ('codigo_acesso', models.CharField(db_index=True, help_text='O código gerado automaticamente que o entrevistador usará como senha.', max_length=20, verbose_name='Código de Acesso')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador do Sistema')),
                ('vaga', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidaturas.vaga', verbose_name='Vaga Alocada')),
            ],
            options={
                'verbose_name': 'historical Entrevistador da Vaga',
                'verbose_name_plural': 'historical Entrevistadores da Vaga',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
