# Generated by Django 6.0 on 2026-03-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0007_entrevistadorvaga_historicalentrevistadorvaga'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaga',
            name='distrito',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Selecione o distrito, caso seja uma vaga Distrital.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='historicalvaga',
            name='provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Selecione a província, caso seja uma vaga Provincial ou Distrital.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.provincia', verbose_name='Província'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='distrito',
            field=models.ForeignKey(blank=True, help_text='Selecione o distrito, caso seja uma vaga Distrital.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='provincia',
            field=models.ForeignKey(blank=True, help_text='Selecione a província, caso seja uma vaga Provincial ou Distrital.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provincia', verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='historicalvaga',
            name='nivel_aprovacao',
            field=models.CharField(choices=[('CENTRAL', 'STAE Central'), ('PROVINCIAL', 'STAE Provincial'), ('DISTRITAL', 'STAE Distrital')], default='DISTRITAL', help_text='Define para onde é a vaga (STAE Central, Provincial ou Distrital).', max_length=20, verbose_name='Destino da Vaga'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='nivel_aprovacao',
            field=models.CharField(choices=[('CENTRAL', 'STAE Central'), ('PROVINCIAL', 'STAE Provincial'), ('DISTRITAL', 'STAE Distrital')], default='DISTRITAL', help_text='Define para onde é a vaga (STAE Central, Provincial ou Distrital).', max_length=20, verbose_name='Destino da Vaga'),
        ),
    ]
