# Generated by Django 6.0 on 2026-02-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField(default=30)),
                ('descricao', models.TextField(blank=True, help_text='Ex: Sala 10, Bloco A - 08:00 às 13:00', null=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_formacao', to='core.distrito')),
            ],
            options={
                'verbose_name': 'Local de Formação',
                'verbose_name_plural': 'Locais de Formação',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_formacao', models.CharField(choices=[('FORMACAO_FORMADORES', 'Formação de Formadores (Provincial)'), ('FORMACAO_BRIGADISTAS', 'Formação de Brigadistas (Distrital)')], default='FORMACAO_BRIGADISTAS', help_text='Formação de Formadores (Provincial) ou Brigadistas (Distrital)', max_length=30, verbose_name='Tipo de Formação')),
                ('numero', models.PositiveIntegerField(help_text='Número da turma dentro do distrito (1 a 35)')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('carga_horaria_prevista', models.PositiveIntegerField(default=40, help_text='Carga horária total prevista em horas', verbose_name='Carga Horária Prevista (horas)')),
                ('carga_horaria_realizada', models.PositiveIntegerField(default=0, help_text='Calculado automaticamente pelas sessões realizadas', verbose_name='Carga Horária Realizada (horas)')),
                ('percentual_presenca_minimo', models.PositiveIntegerField(default=75, help_text='Percentual mínimo de presença para certificação', verbose_name='Presença Mínima (%)')),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=2, default=10.0, help_text='Nota mínima para aprovação (escala 0-20)', max_digits=4, verbose_name='Nota Mínima para Aprovação')),
                ('concluida', models.BooleanField(default=False, verbose_name='Formação Concluída')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.distrito')),
                ('formadores', models.ManyToManyField(blank=True, related_name='turmas_como_formador', to='core.candidatoformacao')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='formacao.local')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['distrito', 'numero'],
                'unique_together': {('distrito', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SessaoFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Sessão')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('tema', models.CharField(help_text='Ex: Primeiros Socorros, Combate a Incêndios, etc.', max_length=200, verbose_name='Tema/Módulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('duracao_horas', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automaticamente', max_digits=4, verbose_name='Duração (horas)')),
                ('realizada', models.BooleanField(default=False, verbose_name='Sessão Realizada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('formador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_ministradas', to='core.candidatoformacao', verbose_name='Formador Responsável')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='formacao.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Sessão de Formação',
                'verbose_name_plural': 'Sessões de Formação',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FORMADOR', 'Formador Certificado'), ('BRIGADISTA', 'Brigadista Certificado')], max_length=20, verbose_name='Tipo de Certificação')),
                ('numero_certificado', models.CharField(help_text='Gerado automaticamente', max_length=50, unique=True, verbose_name='Número do Certificado')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, help_text='Deixe em branco para certificação permanente', null=True, verbose_name='Data de Validade')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Escala 0-20', max_digits=4, null=True, verbose_name='Nota Final')),
                ('percentual_presenca', models.DecimalField(decimal_places=2, help_text='Calculado automaticamente', max_digits=5, verbose_name='Percentual de Presença')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('REVOGADO', 'Revogado'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=20, verbose_name='Estado')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado PDF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='core.candidatoformacao', verbose_name='Candidato')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificacoes_emitidas', to='formacao.turma', verbose_name='Turma de Origem')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='PresencaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa de Falta')),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.candidatoformacao', verbose_name='Candidato')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='formacao.sessaoformacao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Presença em Sessão',
                'verbose_name_plural': 'Presenças em Sessões',
                'ordering': ['sessao', 'candidato__nome_completo'],
                'unique_together': {('sessao', 'candidato')},
            },
        ),
    ]
