# Generated by Django 6.0 on 2026-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('formacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_como_aluno', to='core.candidatoformacao'),
        ),
    ]
