# Generated by Django 6.0 on 2026-02-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0002_turma_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacao',
            name='tipo',
            field=models.CharField(choices=[('FORMADOR', 'Formador Certificado'), ('MMV', 'MMV Certificado'), ('AGENTE_EDUCACAO', 'Agente de Educação Cívica Certificado'), ('BRIGADISTA', 'Brigadista Certificado')], max_length=20, verbose_name='Tipo de Certificação'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_formacao',
            field=models.CharField(choices=[('FORMADORES', 'Formadores'), ('MMV', 'Membros de Mesas de Voto (MMV)'), ('AGENTES_EDUCACAO', 'Agentes de Educação Cívica'), ('BRIGADISTAS', 'Brigadistas')], default='BRIGADISTAS', help_text='Tipo de agente eleitoral: Formadores, MMV, Agentes de Educação Cívica ou Brigadistas', max_length=30, verbose_name='Tipo de Formação'),
        ),
    ]
