# Generated by Django 6.0 on 2026-02-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilutilizador'),
        ('formacao', '0003_alter_certificacao_tipo_alter_turma_tipo_formacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turma',
            name='provincia',
            field=models.ForeignKey(blank=True, help_text='Obrigatório para Formadores Nacionais — indica a Direção Provincial onde ocorre a formação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_provinciais', to='core.provincia', verbose_name='Direção Provincial'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='distrito',
            field=models.ForeignKey(blank=True, help_text='Obrigatório para turmas de campo (Brigadistas, MMV, Educ. Cívica) e Formadores Provinciais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.distrito'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_formacao',
            field=models.CharField(choices=[('FORMADORES_NACIONAIS', 'Formadores Nacionais'), ('FORMADORES_PROVINCIAIS', 'Formadores Provinciais'), ('MMV', 'Membros de Mesas de Voto (MMV)'), ('AGENTES_EDUCACAO', 'Agentes de Educação Cívica'), ('BRIGADISTAS', 'Brigadistas'), ('FORMADORES', 'Formadores (legado)')], default='BRIGADISTAS', help_text='Formadores Nacionais: ocorrem nas Direções Provinciais. Formadores Provinciais: ocorrem a nível da Província. MMV, Brigadistas, Educ. Cívica: ocorrem nos Distritos.', max_length=30, verbose_name='Tipo de Formação'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('distrito', 'numero', 'tipo_formacao')},
        ),
        migrations.CreateModel(
            name='PlanoFormacaoDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_brigadas', models.PositiveIntegerField(help_text='Total de brigadas a funcionar neste distrito', verbose_name='Número de Brigadas')),
                ('margem_contingencia', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentagem adicional de formandos para cobrir desistências. Ex: 5 = 5%', max_digits=5, verbose_name='Margem de Contingência (%)')),
                ('candidatos_por_turma_brigadista', models.PositiveIntegerField(default=30, verbose_name='Candidatos por Turma (Brigadistas)')),
                ('candidatos_por_turma_mmv', models.PositiveIntegerField(default=30, verbose_name='Candidatos por Turma (MMV)')),
                ('candidatos_por_turma_civico', models.PositiveIntegerField(default=30, verbose_name='Candidatos por Turma (Educ. Cívica)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_formacao', to='core.distrito', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Plano de Formação por Distrito',
                'verbose_name_plural': 'Planos de Formação por Distrito',
                'ordering': ['distrito__provincia__nome', 'distrito__nome'],
            },
        ),
    ]
