# Generated by Django 6.0 on 2026-02-23 (fixed operation order)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilutilizador'),
        ('formacao', '0004_add_plano_formacao_tipo_expanded_provincia_turma'),
    ]

    operations = [
        # 1. Adicionar novos campos primeiro
        migrations.AddField(
            model_name='planoformacaodistrito',
            name='candidatos_por_turma',
            field=models.PositiveIntegerField(
                default=30,
                help_text='Número máximo de formandos por turma para este tipo.',
                verbose_name='Candidatos por Turma'
            ),
        ),
        migrations.AddField(
            model_name='planoformacaodistrito',
            name='num_agentes_previstos',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text='(MMV / Agentes de Educ. Cívica) Número total de agentes a formar neste distrito.',
                verbose_name='Nº de Agentes Previstos'
            ),
        ),
        # 2. Adicionar campo tipo ANTES de unique_together
        migrations.AddField(
            model_name='planoformacaodistrito',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('BRIGADISTAS', 'Brigadistas'),
                    ('MMV', 'Membros de Mesas de Voto (MMV)'),
                    ('AGENTES_EDUCACAO', 'Agentes de Educação Cívica'),
                ],
                default='BRIGADISTAS',
                max_length=30,
                help_text='Tipo de agente para o qual se define este plano. Cada tipo tem um plano separado.',
                verbose_name='Tipo de Plano'
            ),
            preserve_default=False,
        ),
        # 3. Alterar distrito: OneToOneField → ForeignKey
        migrations.AlterField(
            model_name='planoformacaodistrito',
            name='distrito',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='planos_formacao',
                to='core.distrito',
                verbose_name='Distrito'
            ),
        ),
        # 4. Alterar campos existentes
        migrations.AlterField(
            model_name='planoformacaodistrito',
            name='margem_contingencia',
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                max_digits=5,
                help_text='Percentagem adicional para cobrir desistências. Ex: 5 = 5%',
                verbose_name='Margem de Contingência (%)'
            ),
        ),
        migrations.AlterField(
            model_name='planoformacaodistrito',
            name='num_brigadas',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text='(Brigadistas) Total de brigadas a funcionar neste distrito. O sistema calcula 3 brigadistas × brigada.',
                verbose_name='Número de Brigadas'
            ),
        ),
        # 5. unique_together — só agora que tipo existe
        migrations.AlterUniqueTogether(
            name='planoformacaodistrito',
            unique_together={('distrito', 'tipo')},
        ),
        # 6. Remover campos antigos
        migrations.RemoveField(
            model_name='planoformacaodistrito',
            name='candidatos_por_turma_brigadista',
        ),
        migrations.RemoveField(
            model_name='planoformacaodistrito',
            name='candidatos_por_turma_civico',
        ),
        migrations.RemoveField(
            model_name='planoformacaodistrito',
            name='candidatos_por_turma_mmv',
        ),
        # 7. Actualizar opções/ordenação do modelo
        migrations.AlterModelOptions(
            name='planoformacaodistrito',
            options={
                'ordering': ['distrito__provincia__nome', 'distrito__nome', 'tipo'],
                'verbose_name': 'Plano de Formação por Distrito',
                'verbose_name_plural': 'Planos de Formação por Distrito'
            },
        ),
    ]
