# Generated by Django 6.0 on 2026-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0005_refactor_plano_formacao_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoformacaodistrito',
            name='estado',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO_RH', 'Submetido aos RH')], default='RASCUNHO', help_text='Indica se o plano ainda está a ser trabalhado (Rascunho) ou se já foi Submetido aos RH.', max_length=20, verbose_name='Estado do Plano'),
        ),
    ]
