# Generated by Django 6.0 on 2026-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0006_planoformacaodistrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoformacaodistrito',
            name='candidatos_por_turma',
            field=models.PositiveIntegerField(default=40, help_text='Número máximo de formandos por turma para este tipo.', verbose_name='Candidatos por Turma'),
        ),
    ]
