# Generated by Django 6.0 on 2026-03-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0007_alter_planoformacaodistrito_candidatos_por_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoformacao',
            name='formador',
        ),
        migrations.RemoveField(
            model_name='sessaoformacao',
            name='turma',
        ),
        migrations.DeleteModel(
            name='PresencaSessao',
        ),
        migrations.DeleteModel(
            name='SessaoFormacao',
        ),
    ]
