# Generated by Django 6.0 on 2026-03-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_deve_alterar_senha_to_perfil'),
        ('formacao', '0008_remove_sessaoformacao_presencasessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Brigada')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigadas', to='core.distrito', verbose_name='Distrito')),
                ('membros', models.ManyToManyField(blank=True, related_name='brigadas_membro', to='core.candidatoformacao', verbose_name='Membros (Brigadistas)')),
            ],
            options={
                'verbose_name': 'Brigada',
                'verbose_name_plural': 'Brigadas',
                'ordering': ['distrito', 'nome'],
                'unique_together': {('distrito', 'nome')},
            },
        ),
    ]
